- name: VM configuration
  hosts: all
  remote_user: root

  tasks:
  - name: Pkg's list updating and curl installing
    shell:
      cmd: apt update && apt install curl -y
 
  - name: UFW startup enabling
    shell:
      cmd: systemctl enable ufw

  - name: UFW starting
    shell:
      cmd: systemctl start ufw

  - name: UFW activation
    ufw:
      state: enabled

  - name: Add UFW rules for port 80
    ufw:
      rule: allow
      port: '80'

  - name: Add UFW rules for port 8080
    ufw:
      rule: allow
      port: '8080'

  - name: Add UFW rules for port 1834
    ufw:
      rule: allow
      port: '1834'
  
  - name: Delete old SSHD config
    shell:
      cmd: rm /etc/ssh/sshd_config

  - name: Copy new SSHD config
    copy:
      src: source/sshd_config
      dest: /etc/ssh/sshd_config

  - name: Installing Docker
    shell:
      cmd: curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh

  - name: Installing Docker-compose (script copying)
    copy:
      src: source/docker-compose.sh
      dest: /root/docker-compose.sh

  - name: Installing Docker-compose (script execution)
    shell:
      cmd: /bin/bash /root/docker-compose.sh

  - name: Copying source files (mkdir)
    shell:
      cmd: mkdir /skillcloud-nginx

  - name: Copying source files (transfer)
    copy:
      src: source/docker-compose.yml
      dest: /skillcloud-nginx/docker-compose.yml


  - name: Copying source files (transfer)
    copy:
      src: source/Dockerfile-balance
      dest: /skillcloud-nginx/Docker-balance

  - name: Copying source files (transfer)
    copy:
      src: source/Dockerfile-site
      dest: /skillcloud-nginx/Docker-site

  - name: Copying source files (transfer)
    copy:
      src: source/index.html
      dest: /skillcloud-nginx/index.html

  - name: Copying source files (transfer)
    copy:
      src: source/nginx.conf
      dest: /skillcloud-nginx/nginx.conf

  - name: Restarting SSH and UFW
    shell:
      cmd: systemctl restart sshd && systemctl restart ufw

  - name: Rebooting VMs
    reboot:

  - name: Building docker-compose file....
